"""Workspace assembly: what the product puts in a project directory.

Two things, both idempotent and both best-effort:

- **`AGENT.md`** — the project's persona plus whatever the model needs to know
  about the tier it is running at.
- **`chmod 0o777` on the project directory** when the tier is `sandbox`. The
  container runs as uid 1000 against the bind-mounted host directory, so a
  directory the agent must write into has to be writable by a uid the host
  knows nothing about.

## `AGENT.md` is a workaround, and saying so is part of the design

Agent definitions are compiled into identity once, at `Client` construction:
the system prompt, the tool set and the child agents are fixed for the life of
the process. A per-project persona has **no runtime seam** — there is nowhere
to put it. So it goes into a file in the workspace, following the same
wayfinding convention an index file does, and the model reads it the way it
reads anything else in the project.

That is a workaround, not a design goal. It can and should be replaced by
per-project `AgentDefinition`s the moment the SDK grows a seam for them; until
then, treating it as intentional architecture would be a lie a later reader
pays for.

Three rules follow from it being a file on the user's disk rather than
configuration inside the process:

- **Idempotent.** The content is a pure function of the project row. Clearing
  the configuration deletes the file rather than leaving a stale one, and an
  unchanged configuration does not rewrite it — a rewrite would churn the
  mtime the artifact panel and the file surface both read.
- **Never blocking.** A read-only directory, a permission error, a full disk:
  assembly logs and returns. A turn that could have run must not be refused
  because a wayfinding file could not be written.
- **Never destructive.** The file carries a generated-by marker, and anything
  at that path *without* the marker is left exactly as it is. Project
  directories are real directories full of the user's real work; a product
  that silently overwrites a file there has broken the promise it is built on.
  (The SDK's own instruction file is `AGENTS.md` — plural — so the two names
  do not collide even before the marker check.)
"""
from __future__ import annotations

import logging
import os
from pathlib import Path

from noeta.agent.host.tiers import SANDBOX
from noeta.agent.store.projects import Project

logger = logging.getLogger(__name__)

# Singular, so it cannot collide with the SDK's own `AGENTS.md` instruction
# file, which `HostConfig.instructions_enabled` loads from the same directory.
AGENT_FILE_NAME = "AGENT.md"

# Present on every file this module writes, and required before it will
# overwrite or delete one. A user's own AGENT.md has no marker and is
# therefore untouchable.
GENERATED_MARKER = "<!-- generated by noeta-agent from the project configuration -->"

# The container facts the model cannot discover for itself and gets wrong
# without being told. Deliberately short: this is read on every turn, so every
# line costs context on every request.
_SANDBOX_GUIDANCE = """\
## Execution environment

Your file and shell tools run inside a Linux container, not on the user's
machine. This project directory is mounted there, so edits you make are real
and visible outside the container.

- Long-running processes must run in the foreground; background shell
  commands are refused under a container.
- A shell timeout returns to you, but does not stop the command inside the
  container.
"""


def render_agent_md(project: Project) -> str:
    """The `AGENT.md` content for a project, or `""` when there is none.

    `local` contributes no guidance on purpose: running against the real
    filesystem is what the model already assumes, so a paragraph saying so is
    context spent to change nothing. A `local` project with no persona
    therefore renders empty, and an empty render deletes the file."""
    sections: list[str] = []
    persona = project.persona.strip()
    if persona:
        sections.append(persona)
    if project.tier == SANDBOX:
        sections.append(_SANDBOX_GUIDANCE.strip())
    if not sections:
        return ""
    return "\n\n".join([GENERATED_MARKER, *sections]) + "\n"


def _is_ours(path: Path) -> bool:
    """Whether an existing file was written by this module.

    Read as bytes-to-text with errors ignored: a binary file at that path is
    not ours, and finding out must not raise."""
    try:
        head = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False
    return head.lstrip().startswith(GENERATED_MARKER)


def write_agent_md(directory: Path, content: str) -> bool:
    """Write (or delete) `AGENT.md`. Returns whether the file changed.

    Total — every failure is logged and reported as "no change" — because the
    caller is on the turn-driving path and has something more important to get
    on with."""
    path = directory / AGENT_FILE_NAME
    try:
        exists = path.is_file()
        if exists and not _is_ours(path):
            logger.info(
                "%s exists and was not written by noeta-agent; leaving it alone", path
            )
            return False
        if not content:
            if not exists:
                return False
            path.unlink()
            return True
        if exists and path.read_text(encoding="utf-8") == content:
            # No rewrite: the mtime is read by the file surface and the
            # artifact panel, and churning it every turn makes an untouched
            # file look freshly edited.
            return False
        path.write_text(content, encoding="utf-8")
        return True
    except OSError:
        logger.warning("could not maintain %s", path, exc_info=True)
        return False


def make_container_writable(directory: Path) -> None:
    """`chmod 0o777` a directory the containerised agent writes into.

    The AIO container runs as a non-root uid the host has no user for, so a
    bind-mounted host directory is otherwise read-only to it — and the failure
    surfaces as an inexplicable permission error from inside a tool, far from
    here. Best-effort: on a filesystem that does not carry unix modes this is
    a no-op, not a reason to refuse the turn."""
    try:
        os.chmod(directory, 0o777)
    except OSError:
        logger.warning("could not make %s container-writable", directory, exc_info=True)


def assemble(project: Project) -> None:
    """Bring a project's directory up to date for the next turn.

    Called on every turn rather than once at project creation, so an edit to
    the persona or the tier applies from the next message — the same "computed
    at seed time" rule the enabled-MCP alias list follows. Idempotent, so the
    repetition costs a stat and a compare.

    Never raises. Every step here is a convenience for the model or the
    container; none of them is a precondition for driving a turn."""
    directory = Path(project.directory)
    try:
        directory.mkdir(parents=True, exist_ok=True)
    except OSError:
        # A project may be created against a directory that does not exist
        # yet, but if it cannot be made the turn is going to fail on its own
        # terms with a much better message than anything we could raise here.
        logger.warning("could not create the project directory %s", directory, exc_info=True)
        return
    if project.tier == SANDBOX:
        make_container_writable(directory)
    write_agent_md(directory, render_agent_md(project))
